[program:dipanddash]
directory=/var/www/dipanddash/food
command=/var/www/dipanddash/food/venv/bin/gunicorn -c /var/www/dipanddash/gunicorn_config.py food.wsgi:application
user=ubuntu
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/dipanddash/logs/gunicorn.log
environment=PATH="/var/www/dipanddash/food/venv/bin",DJANGO_SETTINGS_MODULE="food.settings"

# Grace time for the application to quit
stopwaitsecs=10
